apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: auto-service
type: Opaque
data:
  # Base64 encoded values
  # jwt_secret: mySecretKey12345678901234567890
  # db_password: postgres123
  JWT_SECRET: bXlTdXBlclNlY3JldEtleVRoYXRJc0F0TGVhc3QzMkNoYXJhY3RlcnNMb25n
  DB_PASSWORD: TmlwdW4xMjM=
