apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: auto-service
type: Opaque
data:
  # Base64 encoded values
  # postgres_user: postgres
  # postgres_password: postgres123
  # postgres_db: autoservice
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: TmlwdW4xMjM=
  POSTGRES_DB: YXV0b19zZXJ2aWNl
